variables:
  SCRIPTS_BRANCH: "main-el8"
  CI_SCRIPTS_DIR: "gemini-rtsw-ci"
  GIT_SUBMODULE_FORCE_HTTPS: "true"
  GIT_SUBMODULE_STRATEGY: "recursive"

include:
  - project: 'nsf-noirlab/gemini/rtsw/user-tools/gemini-rtsw-ci'
    ref: 'main-el8'
    file: '.imported-ci.yml'

stages:
  - build
  - deploy

