TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

# Configuration data files are installed in $TOP)/data
DATA += SCSinit.dat
DATA += high.dat
DATA += instConfig.dat
DATA += limits.dat
DATA += low.dat
DATA += pass.dat
DATA += stop.dat
DATA += xforms.dat

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

